name: CI

on:
  push:
# https://pnpm.io/continuous-integration#github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ’¾ Checkout code
        uses: actions/checkout@v4
      # - name: ğŸ“¦ Cache NextJS
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ${{ github.workspace }}/.next/cache
      #     # Generate a new cache whenever packages or source files change.
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-
      - uses: pnpm/action-setup@v4
        name: ğŸ“¦ Install pnpm
        with:
          run_install: false
          version: 10
      - name: ğŸ“¦ Set up Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ” Compile check
        run: tsc --skipLibCheck --noEmit

      - name: ğŸ§¹ Run linter
        run: pnpm lint

      - name: ğŸ§¹ Run formatter
        run: pnpm format:check

      - name: ğŸ§ª Run tests
        run: pnpm test:run
